test pre commit hook

diff --git a/common/git-hooks/pre-commit b/common/git-hooks/pre-commit
--- a/common/git-hooks/pre-commit
+++ b/common/git-hooks/pre-commit
@@ -1,11 +1,22 @@
 #!/bin/sh
-#
-# TO LEARN MORE ABOUT GIT HOOKS
-#
-# The Git documentation is here: https://git-scm.com/docs/githooks
-# Some helpful resources: https://githooks.com
-#
+
+# Check the appsettings.json file is not being checked in.
+# This contains the resource connection string which should not be checked in.
+# If changes are being made to this file that should be checked in then
+# git commit --no-verify can be used.
+if git diff --cached --name-only | grep -qE 'appsettings.json'; then
+  echo '======= COMMIT ERROR =======' >&2
+  echo 'appsettings.json has been staged for commit.' >&2
+  echo 'This often contains the resource connection string which should not be checked in to source control.' >&2
+  echo 'If you do want to check in changes to this file use `git commit --no-verify`.' >&2
+  echo '============================' >&2
+  exit 1;
+else
+  echo 'check passed'
+  exit 0;
+fi
+
 # Invoke the "rush prettier" custom command to reformat files whenever they
 # are committed. The command is defined in common/config/rush/command-line.json
 # and uses the "rush-prettier" autoinstaller.
-node common/scripts/install-run-rush.js prettier || exit $?
+rush prettier || exit $?
