Add breaking change check pipeline

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -123,6 +123,68 @@ jobs:
           path: |
             packages/communication-react/temp/communication-react.api.json
 
+  check_breaking_changes:
+    needs: get_matrix
+    name: Check Breaking Changes
+    if: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'breaking_changes') }}
+    runs-on: ubuntu-latest
+    strategy:
+      matrix: ${{ fromJSON(needs.get_matrix.outputs.matrix) }}
+    steps:
+      # Checks-out your repository under $GITHUB_WORKSPACE so job can access it
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      # Ensure node version is great enough
+      - name: Use Node.js v14.x
+        uses: actions/setup-node@v3
+        with:
+          node-version: '14.x'
+      # Try get node_modules from cache
+      - name: Restore node_modules from cache
+        uses: actions/cache@v3
+        with:
+          path: common/temp/pnpm-store
+          key: ${{ runner.os }}-${{ hashFiles('common/config/rush/pnpm-lock.yaml') }}
+      # Install dependencies
+      - name: Install rush
+        run: npm install -g @microsoft/rush@5.47.0
+      - name: Install dependencies
+        run: rush install
+      # Switch flavor if necessary
+      - name: Switch flavor for stable build
+        id: switch-flavor
+        if: ${{ matrix.flavor == 'stable' }}
+        run: |
+          rush switch-flavor:stable
+          node ./common/scripts/force-build-flavor.mjs stable
+          rush update:stable
+      - name: Check result of flavor switch
+        if: ${{ always() && steps.switch-flavor.outcome == 'failure' }}
+        run: echo "Failed to switch to stable flavor, please make sure you run 'rush update:stable' if dependencies were updated." && exit 1
+      # Checkout the branch to be merged into in PR
+      - name: Checkout base branch
+        run: git checkout ${{ github.event.pull_request.head.ref }}
+      - name: Build base api file
+        run: rush build -t @azure/communication-react
+      - name: Copy api file
+        with:
+          path: packages/communication-react/
+        run: rushx copy-api-snapshot
+      - name: Checkout current branch
+        run: git checkout ${{ github.event.inputs.branch }}
+      # Builds
+      - name: Build current api file
+        run: rush build -t @azure/communication-react
+      - name: Check breaking changes
+        with:
+          path: packages/communication-react/
+        id: breaking-changes
+        run: rushx check-breaking-change
+      - name: Check result of breaking change check
+        if: ${{ always() && steps.switch-flavor.outcome == 'failure' }}
+        run: echo "Breaking changes detected, make sure if that is expected change, then add 'breaking-changes'  label to PR." && exit 1
+
   call_composite_automation_test:
     needs: get_matrix
     name: Call Composite automation test
