Try using cache for workspace.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -15,19 +15,17 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  # get matrix for ci-jobs
   get_matrix:
-    name: Set CI flavors
+    name: Configure Build Flavour Matrix
     runs-on: ubuntu-latest
     outputs:
       matrix: ${{ steps.get-matrix.outputs.matrix }}
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE so job can access it
+      # Check out only necessary files
       - uses: actions/checkout@v4
         with:
           sparse-checkout: |
             common
-      # Ensure node version is great enough
       - name: Use Node.js
         uses: actions/setup-node@v4
         with:
@@ -35,9 +33,9 @@ jobs:
       - id: get-matrix
         run: echo "matrix=$(node ./common/scripts/workflow-read-matrix.mjs)" >> $GITHUB_OUTPUT
 
-  build_packages:
+  pre_build_checks:
     needs: get_matrix
-    name: Build Packages
+    name: Build Readiness Checks
     runs-on: ubuntu-latest
     strategy:
       matrix: ${{ fromJSON(needs.get_matrix.outputs.matrix) }}
@@ -46,32 +44,28 @@ jobs:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
-      # Ensure node version is great enough
+
       - name: Use Node.js
         uses: actions/setup-node@v4
         with:
           node-version: 'lts/*'
-      # Try get node_modules from cache
-      - name: Restore node_modules from cache
-        uses: actions/cache@v3
-        with:
-          path: common/temp/pnpm-store
-          key: ${{ runner.os }}-${{ hashFiles('common/config/rush/pnpm-lock.yaml') }}
-      # Install dependencies
+
       - name: Install rush
         run: npm install -g @microsoft/rush
       - name: Install dependencies
         run: rush install --max-install-attempts 3
-      # Switch flavor if necessary
+
       - name: Switch flavor for build
         id: switch-flavor
         if: ${{ matrix.flavor != 'beta' }}
         run: |
           rush switch-flavor:${{ matrix.flavor }}
           node ./common/scripts/force-build-flavor.mjs ${{ matrix.flavor }}
-      - name: Run dependency update for stable
+
+      - name: Verify stable dependencies
         if: ${{ matrix.flavor == 'stable' }}
         run: rush update:stable
+
       - name: Check result of flavor switch
         if: ${{ always() && steps.switch-flavor.outcome == 'failure' }}
         run: echo "Failed to switch to stable flavor, please make sure you run 'rush update:stable' if dependencies were updated." && exit 1
@@ -81,9 +75,73 @@ jobs:
         # GitHub provides remote branch names as refs.
         run: node common/scripts/changelog/check.mjs origin/${{ github.base_ref }} origin/${{ github.head_ref }}
 
-      # Perform lint check
       - name: Run linter
         run: rush lint
+
+      - name: Cache workspace
+        id: cache-workspace
+        uses: actions/cache/save@v3
+        with:
+          path: |
+            ${{ github.workflow }}
+          key: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.flavor }}
+
+  # Build the packages for all matrix flavours
+  build_packages:
+    needs: [get_matrix, pre_build_checks]
+    name: Build Packages
+    runs-on: ubuntu-latest
+    strategy:
+      matrix: ${{ fromJSON(needs.get_matrix.outputs.matrix) }}
+    steps:
+      # Grab the
+      # # Checks-out your repository under $GITHUB_WORKSPACE so job can access it
+      # - uses: actions/checkout@v4
+      #   with:
+      #     fetch-depth: 0
+      # # Ensure node version is great enough
+      # - name: Use Node.js
+      #   uses: actions/setup-node@v4
+      #   with:
+      #     node-version: 'lts/*'
+      # # Try get node_modules from cache
+      # - name: Restore node_modules from cache
+      #   uses: actions/cache@v3
+      #   with:
+      #     path: common/temp/pnpm-store
+      #     key: ${{ runner.os }}-${{ hashFiles('common/config/rush/pnpm-lock.yaml') }}
+      # # Install dependencies
+      # - name: Install rush
+      #   run: npm install -g @microsoft/rush
+      # - name: Install dependencies
+      #   run: rush install --max-install-attempts 3
+      # # Switch flavor if necessary
+      # - name: Switch flavor for build
+      #   id: switch-flavor
+      #   if: ${{ matrix.flavor != 'beta' }}
+      #   run: |
+      #     rush switch-flavor:${{ matrix.flavor }}
+      #     node ./common/scripts/force-build-flavor.mjs ${{ matrix.flavor }}
+      # - name: Run dependency update for stable
+      #   if: ${{ matrix.flavor == 'stable' }}
+      #   run: rush update:stable
+      # - name: Check result of flavor switch
+      #   if: ${{ always() && steps.switch-flavor.outcome == 'failure' }}
+      #   run: echo "Failed to switch to stable flavor, please make sure you run 'rush update:stable' if dependencies were updated." && exit 1
+
+      # - name: Check the necessary change file has been submitted
+      #   if: ${{ github.event_name == 'pull_request' }}
+      #   # GitHub provides remote branch names as refs.
+      #   run: node common/scripts/changelog/check.mjs origin/${{ github.base_ref }} origin/${{ github.head_ref }}
+
+      - name: Restore workspace
+        id: restore-workspace
+        uses: actions/cache/restore@v3
+        with:
+          path: |
+            ${{ github.workflow }}
+          key: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.flavor }}
+
       # Builds
       - name: Build Packages
         run: rush build -t @azure/communication-react
@@ -93,6 +151,7 @@ jobs:
       - name: Type check test folder
         if: ${{ matrix.flavor == 'beta' }}
         run: cd packages/react-composites && rushx tsc:e2e
+
       # Verify no uncommitted api extractor changes
       - name: API Extractor Check
         if: ${{ always() }}
@@ -106,32 +165,34 @@ jobs:
             git status ${{ matrix.flavor != 'stable' && '**/review/beta/**' ||  '**/review/stable/**'  }}.md -s
             exit 1
           fi
-      # Tree-shaking check
+
       - name: Treeshaking check
         run: rush build --only @internal/check-treeshaking
-      # Typescript version check
+
       - name: Typescript version compatibility check
         run: rush build --only @internal/check-typescript-regression
-      # Ensure all downstream packlet versions are consitent with the base packlet version
+
       - name: Ensure all package versions are consistent
         run: rush ensure-consistent-versions
-      # Tests
+
       - name: Test Packages
         run: rush test:ci-coverage -t @azure/communication-react
         env:
           NODE_OPTIONS: '--max_old_space_size=4096'
+
       - name: Merge all jest test coverage reports from the current branch
         run: npx nyc merge temp/jest/coverage/detailed-report/ temp/jest/current/merge/detailed-full/coverage-report.json
+
       - name: Create a summary report from the detailed report
         run: npx nyc report --temp-dir temp/jest/current/merge/detailed-full/ --report-dir temp/jest/current/merge/summary/ --reporter json-summary
-      # Upload coverage reports which will be consumed later
+
       - name: Upload detailed and summary jest coverage reports
         uses: actions/upload-artifact@v4
         with:
           name: jest-coverage-report-${{ matrix.flavor }}
           path: temp/jest/current/merge/
-      # Upload azure-communication api.md files for easy access
-      - name: Upload communication-react api files
+
+      - name: Upload communication-react API files
         uses: actions/upload-artifact@v4
         with:
           name: communication-react.${{ matrix.flavor }}.api.json
@@ -139,7 +200,7 @@ jobs:
             packages/communication-react/temp/communication-react.api.json
 
   in-progress-feature-validation:
-    needs: build_packages
+    needs: [build_packages, get_matrix]
     name: Check if in progress feature can be removed separately
     runs-on: ubuntu-latest
     steps:
@@ -163,7 +224,7 @@ jobs:
         run: npm install -g @microsoft/rush
       - name: Install dependencies
         run: rush install --max-install-attempts 3
-      # Switch flavor if necessary
+      # Switch flavour
       - name: Switch flavor for beta-release build
         id: switch-flavor
         run: |
