Fail the step if no lock file submitted

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -68,8 +68,8 @@ jobs:
         if: ${{ matrix.flavor == 'stable' }}
         run: rush switch-flavor:stable
       - name: Check result of flavor switch
-        if: ${{ steps.switch-flavor.outcome == 'failure' }}
-        run: echo "Failed to switch to stable flavor, please make sure you run 'rush update:stable' if dependencies were updated."
+        if: ${{ always() && steps.switch-flavor.outcome == 'failure' }}
+        run: echo "Failed to switch to stable flavor, please make sure you run 'rush update:stable' if dependencies were updated." && exit 1
       # Perform changelog check
       - name: Check the necessary change file has been submitted
         run: rush changelog:check
